{"uuid": "07076872-9991-42e3-885c-55659c0ea7d2", "children": ["84a2cc99-9ee8-440f-9098-b2c3fde88e8f", "49e1c4ea-9411-4689-bba9-26c6c67fe07b", "8013307b-3c14-45b9-9b07-f193c2fd5592", "74dc220c-b044-41eb-8578-458910d466f9", "de258553-0751-4eea-9520-b03aeccf5b32", "b28827cf-4061-4cb7-acf1-c5e01fbd831c", "94acc3a2-d7c6-45f4-83d7-6dcfb36c2b85", "33c41623-b2a2-43ae-999a-79802e8b7837", "cc3203de-0020-4df8-9a5f-675d6c3fa73a", "591f659b-5f0c-495a-aac6-f1276af7f00f", "3fee2825-b809-4d6b-97bd-12e0187dff9b"], "befores": [{"name": "web_driver", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='172.26.21.92', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x053D66D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"D:\\Workspace\\pyenv\\lib\\site-packages\\pluggy-0.9.0-py3.7.egg\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Workspace\\pyenv\\lib\\site-packages\\pytest-4.4.0-py3.7.egg\\_pytest\\fixtures.py\", line 935, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Workspace\\pyenv\\lib\\site-packages\\pytest-4.4.0-py3.7.egg\\_pytest\\fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"D:\\Workspace\\pyautomation\\pyautomation\\web\\webtest.py\", line 21, in web_driver\n    self.driver = WebDrivers().get()\n  File \"D:\\Workspace\\pyautomation\\pyautomation\\drivers\\web_drivers.py\", line 85, in get\n    return WebDrivers.__getattribute__(WebDrivers(), browser)\n  File \"D:\\Workspace\\pyautomation\\pyautomation\\drivers\\web_drivers.py\", line 65, in firefox\n    options=options)\n  File \"D:\\Workspace\\pyenv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\Workspace\\pyenv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"D:\\Workspace\\pyenv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"D:\\Workspace\\pyenv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"D:\\Workspace\\pyenv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 402, in _request\n    resp = http.request(method, url, body=body, headers=headers)\n  File \"D:\\Workspace\\pyenv\\lib\\site-packages\\urllib3-1.24.1-py3.7.egg\\urllib3\\request.py\", line 72, in request\n    **urlopen_kw)\n  File \"D:\\Workspace\\pyenv\\lib\\site-packages\\urllib3-1.24.1-py3.7.egg\\urllib3\\request.py\", line 150, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"D:\\Workspace\\pyenv\\lib\\site-packages\\urllib3-1.24.1-py3.7.egg\\urllib3\\poolmanager.py\", line 323, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"D:\\Workspace\\pyenv\\lib\\site-packages\\urllib3-1.24.1-py3.7.egg\\urllib3\\connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"D:\\Workspace\\pyenv\\lib\\site-packages\\urllib3-1.24.1-py3.7.egg\\urllib3\\connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"D:\\Workspace\\pyenv\\lib\\site-packages\\urllib3-1.24.1-py3.7.egg\\urllib3\\connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"D:\\Workspace\\pyenv\\lib\\site-packages\\urllib3-1.24.1-py3.7.egg\\urllib3\\connectionpool.py\", line 638, in urlopen\n    _stacktrace=sys.exc_info()[2])\n  File \"D:\\Workspace\\pyenv\\lib\\site-packages\\urllib3-1.24.1-py3.7.egg\\urllib3\\util\\retry.py\", line 398, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1557218155810, "stop": 1557218160839}], "start": 1557218155810, "stop": 1557218163324}